# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 14, 53, 6, 492206)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 14, 53, 6, 492180)),
        ),
    ]
