# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20160815_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 21, 15, 57, 746844)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 21, 15, 57, 746817)),
        ),
    ]
