# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20160815_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 20, 56, 12, 373845)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 20, 56, 12, 373816)),
        ),
    ]
