# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 19:50
from __future__ import unicode_literals

import blogapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20160815_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blogapp.models.get_upload_file_name, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 21, 50, 49, 472169)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 21, 50, 49, 472140)),
        ),
    ]
