# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20160806_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='blog',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 11, 25, 9, 702207)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 6, 11, 25, 9, 702180)),
        ),
    ]
