# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20160806_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 1, 36, 32, 872260)),
        ),
    ]
